# Generated by Django 4.0.4 on 2022-04-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.candidate'),
            preserve_default=False,
        ),
    ]
