# Generated by Django 4.0.4 on 2022-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_event_event_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='candidate',
        ),
        migrations.AddField(
            model_name='event',
            name='candidate',
            field=models.ManyToManyField(to='polls.candidate'),
        ),
    ]
