# Generated by Django 4.0.4 on 2022-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_event_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateField(),
        ),
    ]
