# Generated by Django 4.0.4 on 2022-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_candidate_candidate_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_picture',
            field=models.ImageField(blank=True, default='blank_picture.png', null=True, upload_to='images/'),
        ),
    ]
